import Link from "next/link";
import { Logo } from "@/components/logo";

export const metadata = {
  title: "Terms of Service — RoastLab",
  description: "RoastLab terms of use.",
};

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)", color: "var(--text-primary)" }}>
      <header style={{ borderBottom: "1px solid var(--border-subtle)", padding: "0 24px", height: 56, display: "flex", alignItems: "center" }}>
        <Link href="/" style={{ textDecoration: "none" }}>
          <Logo size={24} />
        </Link>
      </header>

      <main style={{ maxWidth: 720, margin: "0 auto", padding: "60px 24px 80px" }}>
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--ember)", marginBottom: 12 }}>Legal</p>
          <h1 style={{ fontSize: 36, fontWeight: 900, letterSpacing: "-0.03em", marginBottom: 8 }}>Terms of Service</h1>
          <p style={{ color: "var(--text-dim)", fontSize: 13 }}>Last updated: June 28, 2026</p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 40, fontSize: 14, lineHeight: 1.75, color: "var(--text-secondary)" }}>
          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>1. Service Description</h2>
            <p>RoastLab (&quot;Service&quot;) is an AI-powered tool that analyzes publicly accessible landing pages and provides feedback (&quot;Roast Reports&quot;). The Service is operated by Gratian Technologies.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>2. Acceptable Use</h2>
            <p>You may only submit URLs to websites you own or have explicit permission to analyze. You must not:</p>
            <ul style={{ marginTop: 12, paddingLeft: 20, display: "flex", flexDirection: "column", gap: 6 }}>
              <li>Submit URLs to scrape or harvest competitor data at scale</li>
              <li>Use the Service to generate content that harasses or defames individuals</li>
              <li>Attempt to reverse-engineer, overload, or abuse the API</li>
              <li>Submit URLs to websites containing illegal content</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>3. AI-Generated Content Disclaimer</h2>
            <p>Roast Reports are generated by AI and are provided for informational purposes only. They represent automated analysis, not professional design or legal advice. We make no warranties about accuracy, completeness, or fitness for any particular purpose. Results may vary.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>4. Payments & Refunds</h2>
            <p>Full Report purchases (₹2,499) are processed by Stripe. Reports are delivered immediately upon payment confirmation. Due to the instant delivery of digital content, <strong style={{ color: "var(--text-primary)" }}>all sales are final and non-refundable</strong> unless the report was not delivered due to a technical error on our side. Contact us within 48 hours of purchase if you did not receive your report.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>5. Intellectual Property</h2>
            <p>You retain all rights to the websites you submit. Roast Reports generated for your URL are yours to use. We retain rights to the RoastLab brand, platform, and underlying AI prompts and infrastructure.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>6. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, RoastLab and Gratian Technologies shall not be liable for any indirect, incidental, or consequential damages arising from use of the Service. Our total liability shall not exceed the amount you paid us in the 30 days prior to the claim.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>7. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance. We will notify registered users of material changes by email.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>8. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12, letterSpacing: "-0.02em" }}>9. Contact</h2>
            <p>Questions? Email <a href="mailto:ritesh@gratiantechnologies.com" style={{ color: "var(--ember)", textDecoration: "none" }}>ritesh@gratiantechnologies.com</a></p>
          </section>
        </div>

        <div style={{ marginTop: 60, paddingTop: 24, borderTop: "1px solid var(--border-subtle)" }}>
          <Link href="/" style={{ color: "var(--text-dim)", fontSize: 13, textDecoration: "none" }}>← Back to RoastLab</Link>
        </div>
      </main>
    </div>
  );
}
