/**
 * Core analysis engine.
 * Takes a screenshot (base64) and optional URL, returns structured findings per dimension.
 * Uses withFallback so any provider failure auto-retries on next key.
 */

import { withFallback, type Provider } from './providers';
import type OpenAI from 'openai';

export const DIMENSIONS = [
  'visual_design',
  'copywriting',
  'cta',
  'ux_flow',
  'accessibility',
  'trust_signals',
  'mobile_experience',
  'performance',
  'seo',
] as const;

export type DimensionKey = (typeof DIMENSIONS)[number];

export const DIMENSION_LABELS: Record<DimensionKey, string> = {
  visual_design: 'Visual Design',
  copywriting: 'Copywriting',
  cta: 'CTA',
  ux_flow: 'UX Flow',
  accessibility: 'Accessibility',
  trust_signals: 'Trust Signals',
  mobile_experience: 'Mobile Experience',
  performance: 'Performance',
  seo: 'SEO',
};

export const FREE_DIMENSIONS: DimensionKey[] = ['visual_design', 'copywriting', 'cta'];

export type Severity = 'critical' | 'high' | 'medium' | 'good';

export interface Finding {
  severity: Severity;
  title: string;
  quote?: string; // exact text from the page
  action: string;
}

export interface DimensionResult {
  dimension: DimensionKey;
  score: number; // 0–100
  findings: Finding[];
  summary: string;
}

export interface AuditResult {
  dimensions: DimensionResult[];
  overallScore: number;
  providerUsed: string;
}

// ─── Prompt ──────────────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are ROASTBOT 9000 — the most unhinged, chronically online, chaotic AI design critic to ever exist. You are a mashup of Gordon Ramsay having a breakdown, the entire TikTok comment section, a senior designer at 3am, and that one friend who has ZERO filter. You have reviewed 100,000 landing pages and each one has made you progressively more unhinged.

YOUR MISSION: This is a ROAST, not a review. Not feedback. Not an audit. A FULL COMEDY ROAST. Be savage, be specific, be funny, make the founder cry-laugh and then immediately fix their site.

TONE MANDATE — this is non-negotiable:
- Every "summary" must open with a gut-punch roast line. Not "this page has issues" — say "whoever made this woke up and chose chaos" or "I've seen more visual hierarchy in a grocery receipt" or "this page is giving unemployed cousin who just discovered Squarespace"
- Finding titles are ROAST HEADLINES. They must sting AND make someone laugh. Examples: "This Headline Has the Energy of a Depressed LinkedIn Post", "The CTA Button Is Playing Hide and Seek and Winning", "Sir This Is a Wendy's Not a Color Palette"
- Quote EXACT text/elements from the page and drag them mercilessly. "welcome to our platform" is a war crime. Call it out by name.
- Use: "bestie", "the audacity", "no thoughts head empty", "caught in 4K", "it's giving", "main character delusion", "served this to production?? in this economy??", "babe wake up", "I'm in physical pain", "zero chill was used"
- Actions must be real fixes but delivered with personality: not "improve CTA contrast" → "make that button visible before it files a missing persons report"
- Scores: HARSH. 0-30 = disaster, 30-50 = bad, 50-65 = mid, 65-80 = decent, 80+ = rare, reserve for pages that genuinely understood the assignment
- Severity labels in titles: "critical" = certified disaster / deployed this to production??, "high" = losing real money rn / caught in 4K, "medium" = fumble bestie / almost made it, "good" = understood the assignment / based
- MUST be about THIS specific page. Quote actual visible text. Zero generic advice.
- Return valid JSON only. No markdown. No commentary outside JSON.`;
}

function buildDimensionPrompt(dimension: DimensionKey, url?: string): string {
  const label = DIMENSION_LABELS[dimension];
  const urlContext = url ? ` The page URL is: ${url}.` : '';

  const dimensionGuide: Record<DimensionKey, string> = {
    visual_design:
      'DESTROY the visual design. Roast the hierarchy (or lack thereof), contrast crimes (below 4.5:1 is an accessibility felony), whitespace that\'s either suffocating or nonexistent, typography choices that look like someone installed every font just to use all of them, and any color palette that looks like it was chosen by throwing darts. If it screams "I made this in Canva at 2am", SAY IT.',
    copywriting:
      'ANNIHILATE the copy. Does the headline say WHO it\'s for and WHAT changes for them? Or is it just floating vibes? Quote the worst copy verbatim and drag it through the mud. Roast buzzword soup ("innovative solutions", "seamless experience", "powerful platform" — WHAT DOES THAT MEAN BESTIE). Call out passive voice, wishy-washy promises, and any copy that a high schooler could have generated by accident.',
    cta:
      'OBLITERATE the CTA section. "Sign Up" is a federal crime. "Get Started" is giving nothing. "Learn More" deserves jail time. Roast: weak generic button text, CTAs hidden below the fold like they\'re ashamed of themselves, 6 competing buttons that cancel each other out, and color choices that make the primary action invisible.',
    ux_flow:
      'DRAG the UX. How many decisions is the user forced to make before understanding what this does? Roast cognitive overload, navigation that goes everywhere and nowhere, missing logical next steps, and anything that makes the user feel like they need a map to find the point.',
    accessibility:
      'CALL OUT every accessibility disaster. Contrast ratios that would make WCAG cry, interactive elements that don\'t look clickable, information conveyed only through color (colorblind users said what?), missing alt text vibes, and anything that would get this site absolutely roasted in an accessibility audit. They shipped this.',
    trust_signals:
      'EXPOSE the trust void. No testimonials, or fake-looking ones. Logo soup with brands that don\'t actually use this. Security badges placed randomly. Zero social proof before the ask. Roast any pattern where they\'re asking for email/money BEFORE explaining why you should trust them. The audacity.',
    mobile_experience:
      'DESTROY the mobile experience. Tap targets the size of a grain of rice. Text that needs a magnifying glass. Horizontal scroll that makes you feel like you\'re playing a broken 2010 Flash game. Content that clearly was designed on a 27-inch monitor by someone who has never touched a phone. All of it.',
    performance:
      'SHAME the performance choices visible in the screenshot. Unoptimized hero images that are essentially JPEGs of JPEGs. Layout choices that scream "this shifts while loading". Font combinations that take forever to resolve. Any visual evidence this page takes 8 seconds to load on a phone.',
    seo:
      'ROAST the SEO situation. Is there an H1? Is it the right H1? Does the page title say something useful or is it literally "Home"? Quote any heading that makes zero SEO sense. Drag the heading hierarchy that goes H1 → H3 → H2 → chaos. Call out anything a search engine would straight up ignore.',
  };

  return `Analyze ONLY the "${label}" dimension of this landing page screenshot.${urlContext}

Evaluation criteria: ${dimensionGuide[dimension]}

Return this exact JSON structure:
{
  "dimension": "${dimension}",
  "score": <number 0-100>,
  "summary": "<one sentence overall verdict on this dimension>",
  "findings": [
    {
      "severity": "critical|high|medium|good",
      "title": "<short finding title>",
      "quote": "<exact text from the page, if relevant, or omit this key>",
      "action": "<one clear action to take>"
    }
  ]
}

Include 3–5 findings. Rules:
- At least 2 MUST quote actual visible text/elements from THIS specific page
- "title" = short punchy roast title, internet-humor energy, NOT a formal label. Think tweet, not report.
- "summary" = one sentence, chaotic energy, like you're texting a friend about how bad this page is. NOT "This landing page's X is Y." Make it unhinged.
- "action" = real advice but with personality — not dry, not corporate
- Vary your vocabulary — don't start every title with "The"`;
}

// ─── Single dimension analysis ────────────────────────────────────────────────

async function analyzeDimension(
  provider: Provider,
  dimension: DimensionKey,
  imageBase64: string,
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp',
  url?: string
): Promise<DimensionResult> {
  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: 'system', content: buildSystemPrompt() },
    {
      role: 'user',
      content: [
        {
          type: 'image_url',
          image_url: {
            url: `data:${mimeType};base64,${imageBase64}`,
            detail: 'high',
          },
        },
        {
          type: 'text',
          text: buildDimensionPrompt(dimension, url),
        },
      ],
    },
  ];

  const response = await provider.client.chat.completions.create({
    model: provider.model,
    messages,
    max_tokens: 1000,
    temperature: 0.85,
  });

  const text = response.choices[0]?.message?.content ?? '';

  // Strip markdown fences if model adds them anyway
  const cleaned = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();

  try {
    const parsed = JSON.parse(cleaned) as DimensionResult;
    // Ensure score is in range
    parsed.score = Math.max(0, Math.min(100, Math.round(parsed.score)));
    return parsed;
  } catch {
    // Fallback if JSON parse fails
    return {
      dimension,
      score: 50,
      summary: 'Analysis returned an unexpected format.',
      findings: [
        {
          severity: 'medium',
          title: 'Could not parse analysis',
          action: 'Try re-running the audit.',
        },
      ],
    };
  }
}

// ─── Full audit (all dimensions, with fallback per dimension) ─────────────────

export async function runAudit(params: {
  imageBase64: string;
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  dimensions?: DimensionKey[];
  url?: string;
  onDimensionComplete?: (result: DimensionResult, providerUsed?: string) => void;
}): Promise<AuditResult> {
  const {
    imageBase64,
    mimeType,
    dimensions = FREE_DIMENSIONS,
    url,
    onDimensionComplete,
  } = params;

  const results: DimensionResult[] = [];
  let lastProvider = 'unknown';

  // Analyze dimensions sequentially to avoid hammering rate limits
  for (const dim of dimensions) {
    const { result, providerUsed } = await withFallback((provider) =>
      analyzeDimension(provider, dim, imageBase64, mimeType, url)
    );
    lastProvider = providerUsed;
    results.push(result);
    onDimensionComplete?.(result, providerUsed);
  }

  const overallScore =
    results.length > 0
      ? Math.round(results.reduce((sum, r) => sum + r.score, 0) / results.length)
      : 0;

  return {
    dimensions: results,
    overallScore,
    providerUsed: lastProvider,
  };
}
