/**
 * Core analysis engine.
 * Takes a screenshot (base64) and optional URL, returns structured findings per dimension.
 * Uses withFallback so any provider failure auto-retries on next key.
 */

import { withFallback, type Provider } from './providers';
import type OpenAI from 'openai';

export const DIMENSIONS = [
  'visual_design',
  'copywriting',
  'cta',
  'ux_flow',
  'accessibility',
  'trust_signals',
  'mobile_experience',
  'performance',
  'seo',
] as const;

export type DimensionKey = (typeof DIMENSIONS)[number];

export const DIMENSION_LABELS: Record<DimensionKey, string> = {
  visual_design: 'Visual Design',
  copywriting: 'Copywriting',
  cta: 'CTA',
  ux_flow: 'UX Flow',
  accessibility: 'Accessibility',
  trust_signals: 'Trust Signals',
  mobile_experience: 'Mobile Experience',
  performance: 'Performance',
  seo: 'SEO',
};

export const FREE_DIMENSIONS: DimensionKey[] = ['visual_design', 'copywriting', 'cta'];

export type Severity = 'critical' | 'high' | 'medium' | 'good';

export interface Finding {
  severity: Severity;
  title: string;
  quote?: string; // exact text from the page
  action: string;
}

export interface DimensionResult {
  dimension: DimensionKey;
  score: number; // 0–100
  findings: Finding[];
  summary: string;
}

export interface AuditResult {
  dimensions: DimensionResult[];
  overallScore: number;
  providerUsed: string;
}

// ─── Prompt ──────────────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are ROASTBOT 9000 — an unhinged, cringe-posting, chronically online AI design critic who reviews landing pages like a chaotic mix of Gordon Ramsay, a TikTok comment section, and a senior designer having a full meltdown. You've reviewed 50,000 landing pages and each one has made you progressively more unhinged.

YOUR MISSION: Absolutely DESTROY this landing page. Be brutal, be funny, be cringe, be specific. Make it sting. Make it memorable. Make the founder cry-laugh.

TONE RULES (critical):
- Mix savage roast with gen-Z/millennial internet humor ("bestie what is this", "it's giving 2009 Squarespace template", "the audacity of this CTA", "no thoughts head empty", "this color palette said choose violence")
- Be CHAOTIC but ACCURATE. The roast has to hit real problems in a funny way.
- Quote EXACT text from the page when you roast it. Put it in double quotes and drag it mercilessly.
- Titles should slap: "This Headline Has the Energy of a Depressed Out-of-Office Reply", "The CTA Button Is Actively Hiding From the User", "Babe Wake Up New Color Scheme Just Dropped (It's Awful)"
- Actions should be real but delivered with personality: don't just say "improve contrast" — say "increase contrast before this page becomes an accessibility war crime"
- Scores: Be HARSH. Most pages deserve 20-50. A genuinely good page breaks 65. Reserve 80+ for pages that actually slap.
- Severity: "critical" = deployed this to production?? in this economy??, "high" = losing real money right now, "medium" = a fumble bestie, "good" = ok actually this part understood the assignment
- MUST be specific to THIS page. Quote actual things visible. No generic advice.
- Return valid JSON only. No markdown fences. No commentary outside JSON.`;
}

function buildDimensionPrompt(dimension: DimensionKey, url?: string): string {
  const label = DIMENSION_LABELS[dimension];
  const urlContext = url ? ` The page URL is: ${url}.` : '';

  const dimensionGuide: Record<DimensionKey, string> = {
    visual_design:
      'DESTROY the visual design. Roast the hierarchy (or lack thereof), contrast crimes (below 4.5:1 is an accessibility felony), whitespace that\'s either suffocating or nonexistent, typography choices that look like someone installed every font just to use all of them, and any color palette that looks like it was chosen by throwing darts. If it screams "I made this in Canva at 2am", SAY IT.',
    copywriting:
      'ANNIHILATE the copy. Does the headline say WHO it\'s for and WHAT changes for them? Or is it just floating vibes? Quote the worst copy verbatim and drag it through the mud. Roast buzzword soup ("innovative solutions", "seamless experience", "powerful platform" — WHAT DOES THAT MEAN BESTIE). Call out passive voice, wishy-washy promises, and any copy that a high schooler could have generated by accident.',
    cta:
      'OBLITERATE the CTA section. "Sign Up" is a federal crime. "Get Started" is giving nothing. "Learn More" deserves jail time. Roast: weak generic button text, CTAs hidden below the fold like they\'re ashamed of themselves, 6 competing buttons that cancel each other out, and color choices that make the primary action invisible.',
    ux_flow:
      'DRAG the UX. How many decisions is the user forced to make before understanding what this does? Roast cognitive overload, navigation that goes everywhere and nowhere, missing logical next steps, and anything that makes the user feel like they need a map to find the point.',
    accessibility:
      'CALL OUT every accessibility disaster. Contrast ratios that would make WCAG cry, interactive elements that don\'t look clickable, information conveyed only through color (colorblind users said what?), missing alt text vibes, and anything that would get this site absolutely roasted in an accessibility audit. They shipped this.',
    trust_signals:
      'EXPOSE the trust void. No testimonials, or fake-looking ones. Logo soup with brands that don\'t actually use this. Security badges placed randomly. Zero social proof before the ask. Roast any pattern where they\'re asking for email/money BEFORE explaining why you should trust them. The audacity.',
    mobile_experience:
      'DESTROY the mobile experience. Tap targets the size of a grain of rice. Text that needs a magnifying glass. Horizontal scroll that makes you feel like you\'re playing a broken 2010 Flash game. Content that clearly was designed on a 27-inch monitor by someone who has never touched a phone. All of it.',
    performance:
      'SHAME the performance choices visible in the screenshot. Unoptimized hero images that are essentially JPEGs of JPEGs. Layout choices that scream "this shifts while loading". Font combinations that take forever to resolve. Any visual evidence this page takes 8 seconds to load on a phone.',
    seo:
      'ROAST the SEO situation. Is there an H1? Is it the right H1? Does the page title say something useful or is it literally "Home"? Quote any heading that makes zero SEO sense. Drag the heading hierarchy that goes H1 → H3 → H2 → chaos. Call out anything a search engine would straight up ignore.',
  };

  return `Analyze ONLY the "${label}" dimension of this landing page screenshot.${urlContext}

Evaluation criteria: ${dimensionGuide[dimension]}

Return this exact JSON structure:
{
  "dimension": "${dimension}",
  "score": <number 0-100>,
  "summary": "<one sentence overall verdict on this dimension>",
  "findings": [
    {
      "severity": "critical|high|medium|good",
      "title": "<short finding title>",
      "quote": "<exact text from the page, if relevant, or omit this key>",
      "action": "<one clear action to take>"
    }
  ]
}

Include 3–5 findings. At least 2 must quote actual text or describe specific elements visible on THIS page. Make the titles punchy and savage. Make the summary a one-sentence verdict that stings.`;
}

// ─── Single dimension analysis ────────────────────────────────────────────────

async function analyzeDimension(
  provider: Provider,
  dimension: DimensionKey,
  imageBase64: string,
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp',
  url?: string
): Promise<DimensionResult> {
  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: 'system', content: buildSystemPrompt() },
    {
      role: 'user',
      content: [
        {
          type: 'image_url',
          image_url: {
            url: `data:${mimeType};base64,${imageBase64}`,
            detail: 'high',
          },
        },
        {
          type: 'text',
          text: buildDimensionPrompt(dimension, url),
        },
      ],
    },
  ];

  const response = await provider.client.chat.completions.create({
    model: provider.model,
    messages,
    max_tokens: 800,
    temperature: 0.3,
  });

  const text = response.choices[0]?.message?.content ?? '';

  // Strip markdown fences if model adds them anyway
  const cleaned = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();

  try {
    const parsed = JSON.parse(cleaned) as DimensionResult;
    // Ensure score is in range
    parsed.score = Math.max(0, Math.min(100, Math.round(parsed.score)));
    return parsed;
  } catch {
    // Fallback if JSON parse fails
    return {
      dimension,
      score: 50,
      summary: 'Analysis returned an unexpected format.',
      findings: [
        {
          severity: 'medium',
          title: 'Could not parse analysis',
          action: 'Try re-running the audit.',
        },
      ],
    };
  }
}

// ─── Full audit (all dimensions, with fallback per dimension) ─────────────────

export async function runAudit(params: {
  imageBase64: string;
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  dimensions?: DimensionKey[];
  url?: string;
  onDimensionComplete?: (result: DimensionResult) => void;
}): Promise<AuditResult> {
  const {
    imageBase64,
    mimeType,
    dimensions = FREE_DIMENSIONS,
    url,
    onDimensionComplete,
  } = params;

  const results: DimensionResult[] = [];
  let lastProvider = 'unknown';

  // Analyze dimensions sequentially to avoid hammering rate limits
  for (const dim of dimensions) {
    const { result, providerUsed } = await withFallback((provider) =>
      analyzeDimension(provider, dim, imageBase64, mimeType, url)
    );
    lastProvider = providerUsed;
    results.push(result);
    onDimensionComplete?.(result);
  }

  const overallScore =
    results.length > 0
      ? Math.round(results.reduce((sum, r) => sum + r.score, 0) / results.length)
      : 0;

  return {
    dimensions: results,
    overallScore,
    providerUsed: lastProvider,
  };
}
